const { withAppBuildGradle } = require('expo/config-plugins');

// Windows only: node_modules paths on this machine are long enough that CMake/Ninja's
// generated object-file paths exceed the Windows MAX_PATH limit, which fails native
// builds (e.g. react-native-keyboard-controller). The fix is to point the build at a
// newer ninja binary (installed alongside `cmake;3.31.1` via sdkmanager, with its
// bundled ninja.exe replaced by a build >=1.12 that supports long paths) and raise
// CMake's own object-path safety check. This must live in a config plugin, not a
// hand-edit of android/app/build.gradle, because that folder is regenerated by
// `expo prebuild` and is gitignored.
const IMPORT_MARKER = 'import org.apache.tools.ant.taskdefs.condition.Os';
const FIX_MARKER = 'windows-ninja-fix';

function withWindowsNinjaFix(config) {
  return withAppBuildGradle(config, (config) => {
    let contents = config.modResults.contents;

    if (contents.includes(FIX_MARKER)) {
      return config;
    }

    if (!contents.includes(IMPORT_MARKER)) {
      contents = `${IMPORT_MARKER}\n\n${contents}`;
    }

    const defaultConfigMarker = 'defaultConfig {';
    const insertAt = contents.indexOf(defaultConfigMarker);
    if (insertAt === -1) {
      throw new Error('withWindowsNinjaFix: could not find `defaultConfig {` in android/app/build.gradle');
    }

    const injection = `
        // ${FIX_MARKER}: see plugins/withWindowsNinjaFix.js
        if (Os.isFamily(Os.FAMILY_WINDOWS)) {
            externalNativeBuild {
                cmake {
                    def cmakeDir = "\${android.sdkDirectory}/cmake/3.31.1/bin"
                    def ninjaPath = "\${cmakeDir}/ninja.exe".replace("\\\\", "/")
                    arguments "-DCMAKE_MAKE_PROGRAM=\${ninjaPath}",
                              "-DCMAKE_OBJECT_PATH_MAX=1024"
                }
            }
        }
`;

    const insertPoint = insertAt + defaultConfigMarker.length;
    contents = contents.slice(0, insertPoint) + injection + contents.slice(insertPoint);

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = withWindowsNinjaFix;
